taco:
  orders:
    pageSize: 10


spring:
  data:
    rest:
      base-path: /api

  jms:
    template:
      default-destination: tacocloud.order.queue


tacocloud:
  email:
    host: imap.tacocloud.com
    mailbox: INBOX
    username: taco-in-flow
    password: 1L0v3T4c0s
    poll-rate: 10000
  api:
    url: http://api.tacocloud.com